[package]
name = "Cotodo"
version = "0.1.0"
edition = "2021"

[dependencies]
slint = "*"
reqwest = { version = "*", features = ["json"] }
tokio = { version = "*", features = ["full"] }
serde = { version = "*", features = ["derive"] }
serde_json = "*"
